### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by ghost** [Moliman/tiny-electron#5]
[Deleted]

**Comment by Moliman** [comment]
Hello! I know that it's already been closed, but I wanted to thanks you to take a look on my project, I did it to have a HTML word processor, but when I've realized that I won't have time to maintain it alone, and I've just used MS Word, since, I've stopped the project. I saw that you forked it, I wish you good look with the project. I will sure take a look.

**Comment by Alyw234237** [comment]
Hi Moliman,

Thank you for your email. And thank you for your work and well wishes! I
don't have experience programming in these areas (e.g., Electron) so your
code made it really easy to get started.

I actually ended up switching from Electron to a Progressive Web App and
I'm working on the PWA version now instead:

https://github.com/Alyw234237/text-editor
https://alyw234237.github.io/text-editor/

I made that ticket in mistake—sorry! For some reason paste was only pasting
plain text for me with TinyElectron. It turns out that it was a bug with
Crostini/Linux apps on Chrome OS—not with your code or editor.

Alyssa
